-- MySQL Script generated by MySQL Workbench
-- 10/08/16 06:14:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `userID` INT NOT NULL COMMENT 'Numberical Account #',
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `userType` INT NOT NULL COMMENT '0 = Regular User\n1 = Business Owner',
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organization` (
  `orgID` INT NOT NULL,
  `orgName` VARCHAR(255) NOT NULL,
  `orgAddress` VARCHAR(255) NOT NULL,
  `orgZip` VARCHAR(255) NOT NULL,
  `orgType` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`orgID`),
  CONSTRAINT `Org-UserID`
    FOREIGN KEY (`orgID`)
    REFERENCES `mydb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `userID` INT NOT NULL,
  `locationZip` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`userID`),
  CONSTRAINT `Person-UserID`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `orgID` INT NOT NULL,
  `eventID` INT NOT NULL,
  `eventName` VARCHAR(255) NOT NULL,
  `eventTime` VARCHAR(255) NOT NULL,
  `eventLocation` VARCHAR(255) NOT NULL,
  `eventType` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`orgID`, `eventID`),
  UNIQUE INDEX `eventID_UNIQUE` (`eventID` ASC),
  CONSTRAINT `Event-OrgID`
    FOREIGN KEY (`orgID`)
    REFERENCES `mydb`.`Organization` (`orgID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attendees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attendees` (
  `personID` INT NOT NULL,
  `eventID` INT NOT NULL,
  PRIMARY KEY (`personID`),
  INDEX `Attendee-EventID_idx` (`eventID` ASC),
  CONSTRAINT `Attendee-PersonID`
    FOREIGN KEY (`personID`)
    REFERENCES `mydb`.`Person` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Attendee-EventID`
    FOREIGN KEY (`eventID`)
    REFERENCES `mydb`.`Event` (`eventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`User` (`userID`, `password`, `email`, `userType`) VALUES (1, 'password1', 'test@test.com', 0);
INSERT INTO `mydb`.`User` (`userID`, `password`, `email`, `userType`) VALUES (2, 'password2', 'test2@test.com', 0);
INSERT INTO `mydb`.`User` (`userID`, `password`, `email`, `userType`) VALUES (3, 'password3', 'test3@test.com', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Organization`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Organization` (`orgID`, `orgName`, `orgAddress`, `orgZip`, `orgType`) VALUES (3, 'TestOrg', '123  E. Main St. Newark, DE', '19711', 'Restaurant');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Person`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Person` (`userID`, `locationZip`, `age`, `name`) VALUES (1, '111111', 25, 'Jordan');
INSERT INTO `mydb`.`Person` (`userID`, `locationZip`, `age`, `name`) VALUES (2, '222222', 35, 'John');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Event`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Event` (`orgID`, `eventID`, `eventName`, `eventTime`, `eventLocation`, `eventType`) VALUES (3, 3001, 'TestEvent1', '5:30 P.M', 'Newark, DE', 'Networking');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Attendees`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Attendees` (`personID`, `eventID`) VALUES (1, 3001);

COMMIT;

